---
# tasks file for k8s_master
    
- name: Add kubeadm repositories on Master Node
  yum_repository:
    name: kube
    description: Kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    enabled: 1
    gpgcheck: 1
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Installing Docker & kubeadm on Master Node
  package:
    name:
      - docker
      - kubeadm
      - iproute-tc
    state: present

- name: Staring & enabling Docker & kubelet on Master Node
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ service_names }}"

- name: Pulling the images of k8s master
  command: kubeadm config images pull

- name: Updating Docker cgroup on Master Node
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
      "exec-opts": ["native.cgroupdriver=systemd"]
      }

- name: Restart docker on Master Node
  service:
    name: docker
    state: restarted

- name: Initializing k8s cluster
  command: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem

- name: Setting up kubectl on Master Node
  shell:
    cmd: |        
      mkdir -p  $HOME/.kube
      sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
      sudo chown $(id -u):$(id -g) $HOME/.kube/config

- name: Deploying Flannel on Master Node
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

- name: Creating token for Slave
  command: kubeadm token create  --print-join-command
  register: token

- name: master private dns
  command: curl http://169.254.169.254/latest/meta-data/local-ipv4
  register: master_ip

- name: Setting up NFS on Master Node
  shell:
    cmd: | 
      sudo yum install git -y
      sudo yum install nfs-utils -y
      echo "/ 172.31.0.0/16(rw,sync,no_root_squash)" >>  /etc/exports      
      sudo mkdir /{mysql,html}
      sudo chmod -R 755 /{mysql,html}
      sudo chown nfsnobody:nfsnobody /{mysql,html}
      sudo systemctl enable rpcbind
      sudo systemctl enable nfs-server
      sudo systemctl enable nfs-lock
      sudo systemctl enable nfs-idmap
      sudo systemctl start rpcbind
      sudo systemctl start nfs-server
      sudo systemctl start nfs-lock
      sudo systemctl start nfs-idmap
  
- name: ETCDCTL setup
  shell:
    cmd: |
      ETCD_VER=v3.5.0
      DOWNLOAD_URL=https://storage.googleapis.com/etcd
      mkdir -p /etcdownload
      curl -L ${DOWNLOAD_URL}/${ETCD_VER}/etcd-${ETCD_VER}-linux-amd64.tar.gz -o /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz
      tar xzvf /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz -C /etcdownload --strip-components=1
      rm -f /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz
      mv /etcdownload/etcd /etcdownload/etcdctl /etcdownload/etcdutl /usr/bin
      
- name: Cleaning Caches on RAM
  shell: echo 3 > /proc/sys/vm/drop_caches
# tasks file for k8s_master
